export const phone = '+60107112235'
export const wa = '60107112235'
export const maps = 'https://www.google.com/maps/place/uncommonspace+MY+(Interior+Design)/@3.2040334,101.7460038,17z'
export const tiktok = 'https://www.tiktok.com/@uncommonspacedesign'
export const pitchWa = 'https://wa.me/601151198497'

export const projects = [
  { titleEN: 'Wangsa Melawati Condo', titleMS: 'Kondominium Wangsa Melawati', typeEN: 'Small-space living', typeMS: 'Ruang kecil', img: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80' },
  { titleEN: 'Raw Material Kitchen', titleMS: 'Dapur Bahan Mentah', typeEN: 'Material curation', typeMS: 'Kurasi bahan', img: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80' },
  { titleEN: 'Light Colour Bedroom', titleMS: 'Bilik Tidur Warna Lembut', typeEN: 'Bedroom', typeMS: 'Bilik tidur', img: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200&q=80' },
  { titleEN: 'Texture-Led Dining', titleMS: 'Ruang Makan Bertekstur', typeEN: 'Dining', typeMS: 'Ruang makan', img: 'https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80' },
  { titleEN: 'Compact Study Alcove', titleMS: 'Alkov Belajar Padat', typeEN: 'Work nook', typeMS: 'Sudut kerja', img: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=1200&q=80' },
]

export const dict = {
  en: {
    nav_about: 'About', nav_services: 'Services', nav_work: 'Spaces', nav_process: 'How', nav_contact: 'Visit', nav_cta: 'Book consult',
    hero_issue: 'Issue 01 · Wangsa Melawati',
    hero_title: 'Practical advice. Raw materials. Light colours.',
    hero_sub: 'Spaces that feel like you — even when the footprint is small.',
    hero_cta: 'WhatsApp us', hero_cta2: 'See spaces',
    about_label: 'The studio', about_title: 'Uncommon, on purpose.',
    about_body: 'uncommonspace MY is an interior design studio in Wangsa Melawati, Kuala Lumpur. Clients highlight practical, realistic consultation — even for small spaces — and thoughtful curation of raw materials, light colours, and unique textures that feel modern and inviting.',
    about_designer: 'Interior designer Wada is named in client reviews for material and texture sensibility.',
    services_label: 'What we offer', services_title: 'Consultation first. Curation always.',
    svc1_t: 'Interior consultation', svc1_b: 'Practical, realistic advice before you spend.',
    svc2_t: 'Residential renovation', svc2_b: 'Smooth, timely renovations clients remember fondly.',
    svc3_t: 'Material & texture curation', svc3_b: 'Raw materials, light colours, unique textures.',
    svc4_t: 'Small-space planning', svc4_b: 'Smart layouts when every square metre counts.',
    work_label: 'Spaces', work_title: 'Illustrative interiors',
    work_note: 'Example visuals for this concept site — not claimed as completed uncommonspace projects.',
    work_scroll: 'Scroll →',
    process_label: 'How it works', process_title: 'From chat to curated space.',
    step1_t: 'Consult', step1_b: 'Honest talk about budget, size, and what you love.',
    step2_t: 'Curate', step2_b: 'Materials, colours, and textures chosen with intent.',
    step3_t: 'Plan', step3_b: 'Layouts that respect small and large spaces alike.',
    step4_t: 'Renovate', step4_b: 'Work that stays on track and feels inviting at the end.',
    pull_label: 'From Google',
    pull1: 'Had a very good consultation experience… practical and realistic design advice… even for my small space.',
    pull2: '…interior designer Wada… raw materials, light colours, and unique textures… modern and inviting.',
    pull3: 'I have the best experiences for my house renovation. Everything went smoothly and in a timely manner.',
    contact_label: 'Visit', contact_title: 'Wangsa Melawati, by appointment.',
    contact_hours: 'Mon–Fri 9:00 AM – 5:00 PM · Weekends closed',
    contact_address: 'Jalan Wangsa Melawati 1, Taman Wangsa Melawati, 53300 Kuala Lumpur',
    contact_phone: 'Call', contact_wa: 'WhatsApp', contact_map: 'Maps', contact_tt: 'TikTok',
    footer_pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    footer_pitch_cta: 'Message mr.bagowabair', footer_copy: '© uncommonspace MY · Concept site',
    lang_en: 'EN', lang_ms: 'BM',
  },
  ms: {
    nav_about: 'Tentang', nav_services: 'Perkhidmatan', nav_work: 'Ruang', nav_process: 'Cara', nav_contact: 'Lawat', nav_cta: 'Tempah runding',
    hero_issue: 'Isu 01 · Wangsa Melawati',
    hero_title: 'Nasihat praktikal. Bahan mentah. Warna lembut.',
    hero_sub: 'Ruang yang rasanya seperti anda — walaupun tapaknya kecil.',
    hero_cta: 'WhatsApp kami', hero_cta2: 'Lihat ruang',
    about_label: 'Studio', about_title: 'Uncommon, dengan sengaja.',
    about_body: 'uncommonspace MY ialah studio reka bentuk dalaman di Wangsa Melawati, Kuala Lumpur. Pelanggan menonjolkan perundingan yang praktikal dan realistik — walaupun untuk ruang kecil — serta pemilihan bahan mentah, warna lembut, dan tekstur unik yang moden serta mesra.',
    about_designer: 'Pereka dalaman Wada disebut dalam ulasan pelanggan kerana kepekaan terhadap bahan dan tekstur.',
    services_label: 'Apa yang kami tawar', services_title: 'Perundingan dahulu. Kurasi sentiasa.',
    svc1_t: 'Perundingan dalaman', svc1_b: 'Nasihat praktikal dan realistik sebelum anda belanja.',
    svc2_t: 'Pengubahsuaian kediaman', svc2_b: 'Renovasi lancar dan tepat masa yang dikenang pelanggan.',
    svc3_t: 'Kurasi bahan & tekstur', svc3_b: 'Bahan mentah, warna lembut, tekstur unik.',
    svc4_t: 'Perancangan ruang kecil', svc4_b: 'Susun atur bijak bila setiap meter persegi penting.',
    work_label: 'Ruang', work_title: 'Contoh visual dalaman',
    work_note: 'Visual contoh untuk laman konsep ini — bukan projek siap uncommonspace yang didakwa.',
    work_scroll: 'Tatal →',
    process_label: 'Cara kerja', process_title: 'Dari sembang ke ruang terkuras.',
    step1_t: 'Runding', step1_b: 'Bual jujur tentang bajet, saiz, dan apa yang anda suka.',
    step2_t: 'Kurasi', step2_b: 'Bahan, warna, dan tekstur dipilih dengan niat.',
    step3_t: 'Rancang', step3_b: 'Susun atur yang hormati ruang kecil dan besar.',
    step4_t: 'Ubah suai', step4_b: 'Kerja yang kekal mengikut jadual dan mesra di hujungnya.',
    pull_label: 'Dari Google',
    pull1: 'Pengalaman perundingan sangat baik… nasihat reka bentuk praktikal dan realistik… walaupun untuk ruang kecil saya.',
    pull2: '…pereka dalaman Wada… bahan mentah, warna lembut, dan tekstur unik… moden serta mesra.',
    pull3: 'Pengalaman terbaik untuk pengubahsuaian rumah. Semuanya lancar dan tepat pada masa.',
    contact_label: 'Lawat', contact_title: 'Wangsa Melawati, ikut janji temu.',
    contact_hours: 'Isnin–Jumaat 9:00 pagi – 5:00 petang · Hujung minggu tutup',
    contact_address: 'Jalan Wangsa Melawati 1, Taman Wangsa Melawati, 53300 Kuala Lumpur',
    contact_phone: 'Telefon', contact_wa: 'WhatsApp', contact_map: 'Maps', contact_tt: 'TikTok',
    footer_pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    footer_pitch_cta: 'Mesej mr.bagowabair', footer_copy: '© uncommonspace MY · Laman konsep',
    lang_en: 'EN', lang_ms: 'BM',
  },
} as const
